### ISSUE TITLE
Link to preview the HTML slides doesn't work

### ISSUE THREAD

**Issue by jennybc** [PeteHaitch/2015-09-08_CI-with-bioconductor#1]
:(

**Comment by PeteHaitch** [comment]
Thanks, Jenny. http://htmlpreview.github.io/ seems to choke on this page for whatever reason (larger size? fancy webdev stuff I don't understand?) Moving to http://rawgit.com/ seems to handle it okay. Ironically, I suspect there's some neat way to do this with CI and perhaps publish the HTML to the gh-pages branch - if I figure it out I'll add it to the slides!

**Comment by jennybc** [comment]
If you figure that out and write it up, do share!
